/*
 * File: app/store/ArchivosXAplicacionStore.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Upa_Upa.store.ArchivosXAplicacionStore', {
  extend: 'Ext.data.Store',

  requires: [
    'Upa_Upa.model.ArchivosXAplicacionModel',
    'Ext.data.proxy.Ajax',
    'Ext.data.reader.Json',
    'Ext.data.writer.Json'
  ],

  constructor: function(cfg) {
    var me = this;
    cfg = cfg || {};
    me.callParent([Ext.apply({
      storeId: 'ArchivosXAplicacionStore',
      model: 'Upa_Upa.model.ArchivosXAplicacionModel',
      proxy: {
        type: 'ajax',
        extraParams: {
          idGrid: 'archivos_x_aplicacion'
        },
        url: '../servidor/upaupa/grdread',
        reader: {
          type: 'json',
          rootProperty: 'data',
          metaProperty: 'newId'
        },
        writer: {
          type: 'json',
          encode: true,
          rootProperty: 'data'
        }
      }
    }, cfg)]);
  }
});