/*
 * File: app/view/winArchivos.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Upa_Upa.view.winArchivos', {
  extend: 'Ext.window.Window',
  alias: 'widget.winarchivos',

  requires: [
    'Upa_Upa.view.winArchivosViewModel',
    'Upa_Upa.view.winArchivosViewController',
    'Ext.grid.Panel',
    'Ext.grid.column.Column',
    'Ext.view.Table'
  ],

  controller: 'winarchivos',
  viewModel: {
    type: 'winarchivos'
  },
  height: 370,
  id: 'winArchivos',
  width: 644,
  layout: 'fit',
  title: 'Archivos por subir',
  maximizable: true,

  items: [
    {
      xtype: 'gridpanel',
      id: 'grdArchivos',
      columnLines: true,
      forceFit: true,
      store: 'ArchivosStore',
      columns: [
        {
          xtype: 'gridcolumn',
          dataIndex: 'directorio',
          text: 'Directorio'
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'archivo',
          text: 'Archivo'
        }
      ]
    }
  ],
  listeners: {
    afterrender: 'onWinArchivosAfterRender'
  }

});