/*
 * File: app/view/winDominiosViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Upa_Upa.view.winDominiosViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.windominios',

  loadForm: function(data) {
    let forma = Ext.getCmp('frmDominios').getForm();
    forma.reset(true);
    forma.setValues(data);
  },

  onBtnGrabarClick: function(button, e, eOpts) {
    const forma = Ext.getCmp('frmDominios').getForm();
    const grid = Ext.getCmp('grdDominios');


    if(forma.isValid()){
      Ext.Ajax.request
      (
      {
        url: '../servidor/upaupa/savedomain',
        // A continuación los parámetros
        params: {
          data: Ext.JSON.encode(forma.getValues())
        },
        callback: function(obj, success, response)
        {
          if(success)
          {
            const res = Ext.JSON.decode(response.responseText);
            if(res.success){
              grid.getStore().load();
            }
          }
          else
          Ext.Msg.show
          (
          {
            title: 'ERROR',
            msg: 'Ha ocurrido un error al grabar',
            icon: Ext.Msg.ERROR,
            buttons: Ext.Msg.OK
          }
          );
        }
      }
      );
    }
  },

  onWinDominiosAfterRender: function(component, eOpts) {
    this.loadForm(component.data);
  }

});
