/*
 * File: app/view/winDominios.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Upa_Upa.view.winDominios', {
  extend: 'Ext.window.Window',
  alias: 'widget.winDominios',

  requires: [
    'Upa_Upa.view.winDominiosViewModel',
    'Upa_Upa.view.winDominiosViewController',
    'Ext.form.Panel',
    'Ext.toolbar.Toolbar',
    'Ext.button.Button',
    'Ext.form.FieldSet',
    'Ext.form.field.Hidden',
    'Ext.form.field.ComboBox'
  ],

  controller: 'windominios',
  viewModel: {
    type: 'windominios'
  },
  height: 371,
  id: 'winDominios',
  resizable: false,
  width: 513,
  layout: 'fit',
  title: 'Dominios',

  items: [
    {
      xtype: 'form',
      id: 'frmDominios',
      layout: 'fit',
      bodyPadding: 5,
      fieldDefaults: {
        labelWidth: 120,
        labelAlign: 'right'
      },
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          items: [
            {
              xtype: 'button',
              iconCls: 'x-fa fa-save',
              text: 'Grabar',
              listeners: {
                click: 'onBtnGrabarClick'
              }
            }
          ]
        }
      ],
      items: [
        {
          xtype: 'fieldset',
          items: [
            {
              xtype: 'hiddenfield',
              anchor: '100%',
              fieldLabel: 'Label',
              name: 'id_dominio'
            },
            {
              xtype: 'textfield',
              anchor: '100%',
              fieldLabel: 'Descripción',
              name: 'descripcion_dominio'
            },
            {
              xtype: 'combobox',
              anchor: '100%',
              fieldLabel: 'Estado',
              name: 'estado_dominio',
              store: [
                [
                  'A',
                  'Activo'
                ],
                [
                  'I',
                  'Inactivo'
                ]
              ]
            },
            {
              xtype: 'textfield',
              anchor: '100%',
              fieldLabel: 'Servidor',
              name: 'servidor'
            },
            {
              xtype: 'textfield',
              anchor: '100%',
              fieldLabel: 'Usuario',
              name: 'usuario'
            },
            {
              xtype: 'textfield',
              anchor: '100%',
              fieldLabel: 'Clave',
              name: 'clave',
              inputType: 'password'
            },
            {
              xtype: 'textfield',
              anchor: '100%',
              fieldLabel: 'Directorio FTP',
              name: 'directorio_ftp'
            }
          ]
        }
      ]
    }
  ],
  listeners: {
    afterrender: 'onWinDominiosAfterRender'
  }

});